### ISSUE TITLE
1 を押下するとフォーカスが外れる

### ISSUE THREAD

**Issue by tk42** [Kazunori-Kimura/react-awesome-table#108]
Zennのスクラップから参りました．大変素晴らしいライブラリを公開していただきありがとうございます．

バグと思われる事象を見つけましたので報告いたします．

（編集中でない）セルを選択中のとき，`1` を押下するとセルに格納後フォーカスが外れる

というものです．
M1 Mac 2021 Monterey にて Chrome, Safari, Firefoxで発生を確認しました．

調べた限りでは，`1` を押下したケースでのみ，`handleBlurDocument` が呼び出されていることは確認しましたが，
その根本原因までは特定できませんでした．
ご確認よろしくおねがいします．

## 確認
 - 正常なケース．入力前
<img width="371" alt="Screen Shot 2022-08-27 at 0 15 48" src="https://user-images.githubusercontent.com/8386849/187006271-9e06ccab-a1c0-4a6d-b647-e895ee8c2d30.png">
 - 正常なケース．入力後
<img width="371" alt="Screen Shot 2022-08-27 at 0 15 56" src="https://user-images.githubusercontent.com/8386849/187006274-af646741-fad8-4faf-864b-97df09ad5c6d.png">
 - 異常なケース．入力前
<img width="371" alt="Screen Shot 2022-08-27 at 0 16 02" src="https://user-images.githubusercontent.com/8386849/187006276-3f4314b1-fbba-40dd-8563-da3e2d12309a.png">
 - 異常なケース．入力後．この時フォーカスがはずれているため，入力を続ける場合再度セルを選択する必要がある
<img width="356" alt="Screen Shot 2022-08-27 at 0 16 07" src="https://user-images.githubusercontent.com/8386849/187006277-60b27d2d-9d03-48a3-881f-0c6523abddc7.png">

**Comment by Kazunori-Kimura** [comment]
@tk42 
おそらく Storybook のキーボードショートカットとバッティングしていて、そっちにフォーカスが取られてます。
↓リンクはコンポーネントを全画面表示していますが、ここでは `1` を入力してもフォーカスが失われないです。

https://kazunori-kimura.github.io/react-awesome-table/iframe.html?id=components-table--sample&args=&viewMode=story

**Comment by tk42** [comment]
@Kazunori-Kimura
ありがとうございます！なるほどです！1を入力してもフォーカス失われないことを確認しました！:+1:
